# Generated by Django 5.2 on 2025-05-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allimApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
